*** Starting uWSGI 2.0.18 (64bit) on [Sat Mar 21 12:44:46 2020] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 19 June 2019 03:32:33
os: Darwin-19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
nodename: bogon
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 12
current working directory: /Users/zhiqiang/Desktop/dockertest/docker_test/dockertest
writing pidfile to uwsgi.pid
detected binary path: /Users/zhiqiang/anaconda3/envs/pyserver/bin/uwsgi
chdir() to /Users/zhiqiang/Desktop/dockertest/docker_test/dockertest
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 12800
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:56949 (port auto-assigned) fd 3
Python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Python main interpreter initialized at 0x7f9201002350
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416560 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "dockertest/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/site-packages/django/utils/version.py", line 1, in <module>
    import datetime
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/datetime.py", line 8, in <module>
    import math as _math
ImportError: dlopen(/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5015)
spawned uWSGI worker 1 (pid: 5016, cores: 2)
spawned uWSGI worker 2 (pid: 5017, cores: 2)
spawned uWSGI worker 3 (pid: 5018, cores: 2)
spawned uWSGI worker 4 (pid: 5019, cores: 2)
spawned uWSGI http 1 (pid: 5020)
--- no python application found, check your startup logs for errors ---
[pid: 5019|app: -1|req: -1/1] 127.0.0.1 () {48 vars in 966 bytes} [Sat Mar 21 12:44:56 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 5020)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Sat Mar 21 12:46:47 2020] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 19 June 2019 03:32:33
os: Darwin-19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
nodename: bogon
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 12
current working directory: /Users/zhiqiang/Desktop/dockertest/docker_test/dockertest
writing pidfile to uwsgi.pid
detected binary path: /Users/zhiqiang/anaconda3/envs/pyserver/bin/uwsgi
chdir() to /Users/zhiqiang/Desktop/dockertest/docker_test/dockertest
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 12800
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:57122 (port auto-assigned) fd 3
Python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Python main interpreter initialized at 0x7f986df01ee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416560 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "dockertest/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/site-packages/django/utils/version.py", line 1, in <module>
    import datetime
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/datetime.py", line 8, in <module>
    import math as _math
ImportError: dlopen(/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5324)
spawned uWSGI worker 1 (pid: 5325, cores: 2)
spawned uWSGI worker 2 (pid: 5326, cores: 2)
spawned uWSGI worker 3 (pid: 5327, cores: 2)
spawned uWSGI worker 4 (pid: 5328, cores: 2)
spawned uWSGI http 1 (pid: 5329)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 5329)
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Sat Mar 21 12:47:18 2020] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 19 June 2019 03:32:33
os: Darwin-19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
nodename: bogon
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 12
current working directory: /Users/zhiqiang/Desktop/dockertest/docker_test/dockertest
writing pidfile to uwsgi.pid
detected binary path: /Users/zhiqiang/anaconda3/envs/pyserver/bin/uwsgi
chdir() to /Users/zhiqiang/Desktop/dockertest/docker_test/dockertest
your processes number limit is 2784
your memory page size is 4096 bytes
detected max file descriptor number: 12800
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:57152 (port auto-assigned) fd 3
Python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Python main interpreter initialized at 0x7fa3a27024c0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416560 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
<module 'posixpath' from '/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/posixpath.py'>
Traceback (most recent call last):
  File "dockertest/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/site-packages/django/utils/version.py", line 1, in <module>
    import datetime
  File "/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/datetime.py", line 8, in <module>
    import math as _math
ImportError: dlopen(/Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/zhiqiang/anaconda3/envs/pyserver/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5422)
spawned uWSGI worker 1 (pid: 5423, cores: 2)
spawned uWSGI worker 2 (pid: 5424, cores: 2)
spawned uWSGI worker 3 (pid: 5425, cores: 2)
spawned uWSGI worker 4 (pid: 5426, cores: 2)
spawned uWSGI http 1 (pid: 5427)
